version: '3'

services:
  # Frontend service configuration
  frontend:
    container_name: ng_frontend
    build: ./Front
    ports:
      - 4200:4200
    working_dir: /app-frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:9000  # Modifier le port pour correspondre au backend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:4200"]
      timeout: 10s
      retries: 5

  # Backend service configuration
  backend:
    container_name: ng_backend
    build: ./Backend
    ports:
      - 9000:9000
    working_dir: /app-backend
    environment:
      - APP_PORT=9000
      - JWT_SECRET=jwt_secret
      - MONGODB_URI=mongodb+srv://root:root@cluster0.bdozs6y.mongodb.net/pfa?retryWrites=true&w=majority
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:9000"]
      timeout: 10s
      retries: 5
